### ISSUE TITLE
XMPP Server

### ISSUE THREAD

**Issue by ktrev** [GabrielRivera21/Firebase-Backend-Node-JS#1]
How to use the XMPP server in this?
Can  I send upstream and downstream messages using this?

**Comment by GabrielRivera21** [comment]
Yes, you can. Right now in the demo once you have your server running, you would send a POST request to `/api/send/xmpp` with the required JSON fields in order to downstream. 

https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_to_specific_devices

If you need to upstream, just follow Google's doc on how to send an upstream message and you should receive it on the server.

https://firebase.google.com/docs/cloud-messaging/android/upstream#send_an_upstream_message_from_an_android_client_app
